kongDeploymentName: kong-ingress-controller
kongServiceName: kong-ingress-controller-service

replicas: 1

image: kong
imageTag: latest

host: example.com

ports:
- name: https
  port: 8443
  targetPort: 8443

serviceType: ClusterIP

ingressAnnotations:
  nginx.ingress.kubernetes.io/ssl-redirect: "true"
  nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  nginx.ingress.kubernetes.io/secure-backends: "true"

ingressPath: /
