apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kongServiceName }}
spec:
  selector:
    app: {{ .Values.kongDeploymentName }}
  ports:
  {{- range .Values.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .port }}
  {{- end }}
  type: {{ .Values.serviceType }}
